{{- if not .Values.st2.existingApiKeysSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackstorm-ha.secrets.st2ApiKeys" . }}
  annotations:
    description: A list of StackStorm API keys with metadata that will be imported into the system
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
type: Opaque
data:
  apikeys.yaml: {{ toYaml .Values.st2.apikeys | b64enc | quote }}
{{- end }}
